# Default values for python-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

primarydb:
  enabled: true
  service:
    type: NodePort
    port: 5432
  replicaCount: 1

  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "10"
  persistentVolume:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    volumeName: primarydb
    storageClass: hostpath
    mountPath: /home/shashank/study/web/python-app-microservice-main/testmount/primarydb/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
      

readreplica:
  enabled: true
  service:
    type: NodePort
    port: 5432
  replicaCount: 1

  image:
    repository: postgres
    pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
    tag: "10"
  persistentVolume: 
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    volumeName: standbydb
    storageClass: hostpath
    mountPath: /home/shashank/study/web/python-app-microservice-main/testmount/standbydb
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

pythonapp:
  enabled: true
  service:
    type: LoadBalancer
    port: 8080
  replicaCount: 1

  image:
    repository: shashank30mishra/test_web
    pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
    tag: app-${{ github.run_number }}
  # smtpUser: admin@domain.com
  # smtpPass: example
  # smtpServer: smtp.domain.com
  # smtpPort: 25
  # smtpUseTls: false
  # smtpUseSsl: false

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

global:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  dbPassword: "123456"
  dbUser: admin
  dbName: python-app
  admpass: "12345"
  
  ingress:
    enabled: true
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      host: blog.domain.com
      path: /
      pathType: Prefix
    # tls: []



